aesd-char-driver : loader script changes
Signed-off-by: aditya <aditya@Ubuntu.myguest.virtualbox.org>

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -20,6 +20,9 @@ else
 fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
-mknod /dev/${device} c $major 0
+mknod /dev/${device} c $major 0 || { 
+    echo "Error: failed to create /dev/${device}"; 
+    exit 1; 
+}
 chgrp $group /dev/${device}
 chmod $mode  /dev/${device}
